// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgFA7LZ_XFewF3ZBb_RNCUiiAbS12UZAM',
    appId: '1:414371471832:web:a081f69189d7f8f62112ad',
    messagingSenderId: '414371471832',
    projectId: 'multi-store-inventory-app',
    authDomain: 'multi-store-inventory-app.firebaseapp.com',
    storageBucket: 'multi-store-inventory-app.firebasestorage.app',
    measurementId: 'G-C96HK5XVKB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVhYnPlLEYct3bVxuOMj769OSc0bUu5z0',
    appId: '1:414371471832:android:2841e6bf8f42e96d2112ad',
    messagingSenderId: '414371471832',
    projectId: 'multi-store-inventory-app',
    storageBucket: 'multi-store-inventory-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjuYd6VB1uXri6wcfDw5IgYasIjhwv44M',
    appId: '1:414371471832:ios:b4e2ad12034dca802112ad',
    messagingSenderId: '414371471832',
    projectId: 'multi-store-inventory-app',
    storageBucket: 'multi-store-inventory-app.firebasestorage.app',
    iosBundleId: 'com.example.multiStoreInventoryRebuild',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjuYd6VB1uXri6wcfDw5IgYasIjhwv44M',
    appId: '1:414371471832:ios:b4e2ad12034dca802112ad',
    messagingSenderId: '414371471832',
    projectId: 'multi-store-inventory-app',
    storageBucket: 'multi-store-inventory-app.firebasestorage.app',
    iosBundleId: 'com.example.multiStoreInventoryRebuild',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCi496sLFa_SdgxbG3j4di_lHjtW3zg7tI',
    appId: '1:414371471832:web:60f0cde458f84f702112ad',
    messagingSenderId: '414371471832',
    projectId: 'multi-store-inventory-app',
    authDomain: 'multi-store-inventory-app.firebaseapp.com',
    storageBucket: 'multi-store-inventory-app.firebasestorage.app',
    measurementId: 'G-N886WSSC8V',
  );
}
